### ISSUE TITLE
[Bug?] SetBackingField(…) fails to build with method calls as argument

### ISSUE THREAD

**Issue by tuffff** [tom-englert/AutoProperties.Fody#1]
When I try to use the SetBackingField extension method with anything more complicated than a simple variable, the build fails. Sometimes with an “Invalid usage of …” message, sometimes with something unrelated.

It works fine using the BypassAutoPropertySettersInConstructorsAttribute. Also, an obvious workaround is to just extract the variable.

Example:
```
public class TestClass {
	public int X { get; set; }
	public TestClass() {
		X.SetBackingField(1); // Works
		X.SetBackingField(Math.Abs(1)); // Fails <===
		var value = Math.Abs(1);
		X.SetBackingField(value); // Works
	}
}

[BypassAutoPropertySettersInConstructors(true)]
public class TestClassWithAttribute {
	public int X { get; set; }
	public TestClassWithAttribute() {
		X = 1; // Works
		X = Math.Abs(1); // Works
	}
}
```

PS: Thanks for this project 👍

**Comment by tom-englert** [comment]
Currently it can't handle complex arguments, but maybe I got an idea how to improve this.
For now I will try to improve the error message. 
Do you have a sample when the build fails with "something unrelated"?

**Comment by tuffff** [comment]
> Do you have a sample when the build fails with "something unrelated"?

Sorry, I think that was a mistake on my part, couldn't reproduce it. Likely errors coming from a dependent project threw me off there.

**Comment by tuffff** [comment]
Thank you very much! :smiley:
