### ISSUE TITLE
Question: would i be able to use this for the following constructs?

### ISSUE THREAD

**Issue by sommmen** [tom-englert/AutoProperties.Fody#14]
Hi,

I sometimes use 'set only' properties, that base themself on the value of another property. Could i use autoproperties to reduce code? See the code below to see what i'm doing:

```
        private AppSettings _appSettings;

        private DirectoryInfo _staticFileDirPath;

        public DirectoryInfo StaticFileDirPath => _staticFileDirPath ??= new DirectoryInfo(_appSettings.StaticFileConfigSection.StaticFileDirFullPath);

        public AnalyticsFileController(IOptions<AppSettings> appSettingsAccessor)
        {
            _appSettings = appSettingsAccessor?.Value ?? throw new ArgumentNullException(nameof(appSettingsAccessor));

        }
```

**Comment by sommmen** [comment]
In  this case staticFileDirpath gets initialized when it is accessed and null, only one time based on the value in Appsettings.

Perhaps fody.Autoproperties could simplify this process?

**Comment by tom-englert** [comment]
I think you are looking for
https://github.com/tom-englert/Lazy.Fody
