### ISSUE TITLE
How to make `SetBackingField` outside of constructor?

### ISSUE THREAD

**Issue by GF-Huang** [tom-englert/AutoProperties.Fody#17]
![image](https://user-images.githubusercontent.com/4510984/162577040-9a876f9e-1e50-4f5b-986f-3122edfb6419.png)

![image](https://user-images.githubusercontent.com/4510984/162577069-49f7bb8b-c860-4a5a-bc8e-35c7e636c72a.png)

**Comment by tom-englert** [comment]
Please provide a PR with a failing unit test. Screen shots of Chinese messages are not helpful.

**Comment by GF-Huang** [comment]
`Invalid usage of extension method ... of class <SearchCode>d__22`, apparently it incorrectly recognizes the method name as a class name.

**Comment by tom-englert** [comment]
I think this is because inlining too much inside the call. Try
```
var x = ExpirationDates.....
SelectedDate.SetBackingField(x);
```
