### ISSUE TITLE
Sequence contains no matching element error on compile

### ISSUE THREAD

**Issue by HappyTreesDev** [tom-englert/AutoProperties.Fody#4]
I seem to be having the same issue that NullGuard.Fody had a bit ago in this https://github.com/Fody/NullGuard/issues/17

Could this be fixed?

**Comment by tom-englert** [comment]
Are you targeting Netstandard?

**Comment by HappyTreesDev** [comment]
Yes I am

**Comment by tom-englert** [comment]
NetStandard supported in v1.9
