### ISSUE TITLE
Set interceptor is not invoked by auto property initializer, or for get-only properties assigned in the ctor

### ISSUE THREAD

**Issue by bccv1** [tom-englert/AutoProperties.Fody#6]
Hi - i have been using this package a lot over the past months, and really appreciate the effort that has gone into it. Just reporting a couple of issues that i've noticed, can reproduce in v1.10.

As per title (both may be the same issue), the property backing field is assigned directly, not via the set interceptor. The get interceptor works as expected in all cases.

```csharp
public class TestClass
{
  public int PropWithGetSet { get; set; }
  public int PropWithGetOnly { get; }
  public int PropWithGetSetInit { get; set; } = 1;  // broken
  public int PropWithGetOnlyInit { get; } = 1;  // broken

  public int countGet;
  public int countSet;

  public TestClass()
  {
    this.PropWithGetSet  = 1;  // works
    this.PropWithGetOnly = 1;  // broken

    Debug.Assert( this.countSet == 4 );  // fails, countSet is 1

    int temp;
    temp = this.PropWithGetSet;
    temp = this.PropWithGetOnly;
    temp = this.PropWithGetSetInit;
    temp = this.PropWithGetOnlyInit;

    Debug.Assert( this.countGet == 4 );  // passes
  }

  [GetInterceptor]
  protected T GetInterceptor<T>( PropertyInfo propInfo, ref T fieldValue )
  {
    this.countGet++;
    return fieldValue;
  }

  [SetInterceptor]
  protected void SetInterceptor<T>( T newValue, PropertyInfo propInfo, ref T fieldValue )
  {
    this.countSet++;
    fieldValue = newValue;
  }
}
```

Thanks!

**Comment by tom-englert** [comment]
Looking at https://github.com/tom-englert/AutoProperties.Fody/blob/master/Tests/InterceptorTests.cs#L55 and https://github.com/tom-englert/AutoProperties.Fody/blob/master/AutoProperties.Fody/PropertyAccessorWeaver.cs#L308 this behavior is intended. If you don't use a ref to the backing field in the interceptors, you will get an exception that this is not supported.
In the cases you describe as broken the compiler does not call the setter but directly assigns the value to the backing field, and the interceptors do not change this default behavior. If you'd like a different behavior, you can use https://github.com/tom-englert/AutoProperties.Fody/blob/master/BackingFieldAccess.md#opting-out-again-with-the-setproperty-extension-method

**Comment by tom-englert** [comment]
Also as the name implies, the SetInterceptor intecepts the property setter - so if you have a **get only** property, why would you expect the setter to be called?

**Comment by bccv1** [comment]
```csharp
    public class Test
    {
      public string One { get; } = "defaultOne";        // a) set property not intercepted
      public string Two { get; set; } = "defaultTwo";   // b) set property not intercepted

      public Test( bool flag )
      {
        if( flag )
        {
          this.One = "otherOne";  // c) set property not intercepted
          this.Two = "otherTwo";  // d) set property intercepted
        }
      }
    }
```

I wasn't sure how auto property initializers were implemented behind the scenes. I was guessing they were executed as part of the ctor like other instance field initializers**, and figured maybe a)/b) and c)/d) were similar.

> Also as the name implies, the SetInterceptor intecepts the property setter - so if you have a get only property, why would you expect the setter to be called?

I guess i was expecting the SetInterceptor to intercept setting the property value, regardless of how the internals are implemented (it looks the same to the developer). Auto properties are a convenience to avoid needing to know about their implementation. Certainly b) feels like maybe it should, but no big deal if you disagree or it's too much work.

> SetProperty extension method

In  my specific case i only control the base class (where the interception occurs) and the issues occurs in subclasses where the subclass-developers don't need to know anything about interception. In any case, i'm not too concerned about c), just pointing it out.

.

\** Yep, seems like they are:

```csharp
    public class TestInit
    {
      public string One { get; } = "foo";

      internal int two;

      public TestInit()
      {
        two = 2;
      }
    }


    public class Tester
    {
      [Test]
      public void Test()
      {
        Type type = typeof( TestInit );

        TestInit instance = (TestInit)FormatterServices.GetUninitializedObject( type );

        Debug.Assert( instance.One == null );
        Debug.Assert( instance.two == 0 );

        type.GetConstructor( Type.EmptyTypes ).Invoke( instance, null );

        Debug.Assert( instance.One == "foo" );
        Debug.Assert( instance.two == 2 );
      }
    }
```

**Comment by tom-englert** [comment]
a) and c) would be extremely hard to fix, since a setter simply does not exist in IL, and would have to be generated first.
You have to think of inline initialization like just having a default value, thus it's bypassing the setter also in b)

Also be aware that if s.o. derives from you class in a different assembly, and does not weave it with AutoProperties.Fody, no interception will take place, so users of your base class must anyhow be aware of this.

**Comment by bccv1** [comment]
> a) and c) would be extremely hard to fix, since a setter simply does not exist in IL, and would have to be generated first.

Yep, I understand, and don't think this would be worth the effort, so happy to ignore these.

> You have to think of inline initialization like just having a default value, thus it's bypassing the setter also in b)

In my mind, intercepting the assignment of the default value makes sense. Consider a class that doesn't use the backing fields at all - say all properties are intercepted and backed by another custom store. In that scenario you also want to intercept the setting of the default value, otherwise the default value will go to an unused backing field, and all other get/set's will go to the custom backing store.

```csharp
    public interface IStore
    {
      void StoreValue( string key, object value );
      object RetrieveValue( string key );
    }

    public abstract class StoreBackedClass
    {
      private IStore backingStore;
      
      [GetInterceptor]
      protected object GetInterceptor( PropertyInfo propInfo )
        => this.backingStore.RetrieveValue( propInfo.Name );

      [SetInterceptor]
      protected void SetInterceptor( PropertyInfo propInfo, object newValue )
        => this.backingStore.StoreValue( propInfo.Name, newValue );
    }

    // elsewhere...
    public class User : StoreBackedClass
    {
      public string Name { get; set; }
      public int Id { get; set; }
      public bool IsEnabled { get; set; } = true;  // assigns "true" to (unused) field
    }

    var user = new User();
    bool isUserEnabled = user.IsEnabled;  // retrieves "false" from backing store
```

Using the ctor to assign the default value (which feels like it should be logically equivalent) will instead work:

```csharp
      public User()
      {
        this.IsEnabled = true;  // stores "true" in backing store
      }
```

> Also be aware that if s.o. derives from you class in a different assembly, and does not weave it with AutoProperties.Fody, no interception will take place, so users of your base class must anyhow be aware of this.

Yep, i have run into this :) Currently i have this in the base ctor:

```csharp
#if DEBUG  // perform some extra checks in the debug build
      // check Fody.AutoProperties weaver has been executed (otherwise will silently fail)
      var field = this.instanceType.Assembly.GetType( "ProcessedByFody" )
        ?.GetField( "AutoProperties", BindingFlags.Static | BindingFlags.NonPublic );
      if( field == null )
        throw new AppException( $"The assembly '{this.instanceType.Assembly.Name()}' that contains Foo " +
          $"subclass '{this.instanceType.Name}' must have the nuget package 'Fody.AutoProperties' installed and " +
          $"configured in FodyWeavers.xml." );
#endif
```

**Comment by bccv1** [comment]
Thanks!! This is great - i really appreciate this update, adding basic support for property initialisers is a big improvement.

Sorry to be a pain, but this addition:

https://github.com/tom-englert/AutoProperties.Fody/commit/58d0ad9688341ea499cf94f775ea4abb3aebb1e5#diff-06d695121114b7ae7af045245a490b92R224

is breaking my code with many compile time errors. I still need to be able to intercept get-only properties to perform eager or lazy value-initialisation. I'd also like to avoid having to ask consumers of my base class to use [InterceptIgnore] when i can just have my interceptors default to get/set the backing field programmatically as required.

Here's an example that works before 1.12:

```csharp
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using AutoProperties;

namespace TestIntercept
{
  // Install-Package AutoProperties.Fody -Version 1.11

  public class MyBase
  {
    public MyBase()
    {
      // auto initialise any get-only properties

      foreach( PropertyInfo prop in GetType().GetProperties().Where( x => !x.CanWrite ) )
      {
        if( prop.Name.Contains( "Lazy" ) )
          continue;  // we'll lazy init in the GetInterceptor below instead

        SetBackingField( prop.Name, "autoInitValue" );
      }
    }

    [GetInterceptor]
    protected T GetInterceptor<T>( PropertyInfo propInfo, ref T fieldValue )
    {
      // lazy initialise any get-only properties on first access

      if( fieldValue == null )  // simplified version...
        fieldValue = (T)(object)"lazyInitValue";

      return fieldValue;
    }

    [SetInterceptor]
    protected void SetInterceptor<T>( PropertyInfo propInfo, ref T fieldValue, T newValue )
    {
      fieldValue = newValue;
    }

    private void SetBackingField( string propName, object value )  // simplified version...
    {
      FieldInfo fieldInfo = GetType().GetField( $"<{propName}>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic );

      Debug.Assert( fieldInfo != null );
      Debug.Assert( fieldInfo.IsInitOnly );

      fieldInfo.SetValue( this, value );  // note we can still set a readonly/IsInitOnly field just fine via reflection
    }
  }


  // elsewhere, someone consumes MyBase

  public class TestOne : MyBase
  {
    public string MyAutoInitProp { get; }

    public string MyLazyInitProp { get; }

    // v1.12, now without [InterceptIgnore], these fail to build with:
    // Error: Fody/AutoProperties: Error intercepting System.String TestIntercept.TestOne::MyAutoInitProp():
    //        Can't use a reference to a read only field: System.String TestIntercept.TestOne::<MyAutoInitProp>k__BackingField
  }


  public static class Program
  {
    public static void Main( string[] args )
    {
      var test = new TestOne();

      Debug.Assert( test.MyAutoInitProp == "autoInitValue" );
      Debug.Assert( test.MyLazyInitProp == "lazyInitValue" );
    }
  }
}
```

**Comment by bccv1** [comment]
Works perfectly! Thank you again, this is super useful.

**Comment by tom-englert** [comment]
Yes :smile:, I just never used the backing field, only a backing store...
